### ISSUE TITLE
Generated play json does not compile due to implicit writer conflict

### ISSUE THREAD

**Issue by zcohn** [mbryzek/apidoc#384]
The generated `Play 2.x json` of the following `api.json` will not compile due to a conflict between the implicit writers.

###### api.json
    {
      "name": "ambiguous-implicit-values-test",
      "description": "ambiguous implicit values test",
      "unions": {
        "container": {
          "types": [
            {
              "type": "serializable"
            }
          ]
        }
      },
      "models": {
        "model": {
          "fields": [
            {
              "name": "name",
              "type": "serializable"
            }
          ]
        }
      },
      "enums": {
        "serializable": {
          "name": "serializable",
          "values": [
            {
              "name": "CONSTANT"
            }
          ]
        }
      }
    }

###### Error
    [error]  package.scala:97: ambiguous implicit values:
    [error]  both value jsonWritesAmbiguousImplicitValuesTestSerializable in package json of type => play.api.libs.json.Writes[com.gilt.ambiguous.implicit.values.test.v0.models.Serializable]{def writes(x: com.gilt.ambiguous.implicit.values.test.v0.models.Serializable): play.api.libs.json.JsString}
    [error]  and method jsonWritesAmbiguousImplicitValuesTestContainer in package json of type => play.api.libs.json.Writes[com.gilt.ambiguous.implicit.values.test.v0.models.Container]
    [error]  match expected type play.api.libs.json.Writes[com.gilt.ambiguous.implicit.values.test.v0.models.Serializable]
    [error]       "name" -> play.api.libs.json.Json.toJson(x.name)

**Comment by mbryzek** [comment]
thanks for the great bug report - looking at this now

**Comment by mbryzek** [comment]
Bug fix for this specific example (model w/ single field) is at https://github.com/mbryzek/apidoc-generator/pull/58

And a branch demonstating same issue when model has multiple fields is here:

https://github.com/mbryzek/apidoc-generator/tree/issue_384_two_fields

[not sure of best approach there yet]

curious does the initial fix solve your immediate problem?

**Comment by k4sbasia** [comment]
@zcohn we are still having issue with the client from affinity, @kevinoriordan can provide more details

**Comment by zcohn** [comment]
@mbryzek This doesn't -- the main source of the problem in our case is model reuse at different levels of the union type hierarchy. (We can work around this with different models and the generated code is correct, or by modifying the generated code to specify the reader/writer rather than relying on the implicit.)

**Comment by mbryzek** [comment]
OK - so this is a bit tricky due to the implicits..

I have one thought I'd like to explore - independently, planning to add a discriminator field to the union types. This will be optional for backwards compatibility - but if present will flatten the json injecting the type discriminator field. Roughly:

"user" => { ... }

can become:

{
  "type": "user",
  ...
}

With this approach, I think we can just NOT providing implicit model writes and instead just use the union type model writers all the time. The end result is every time you write the model, you will see the discriminator field - but I think it will fully avoid the situation where multiple implicits can match (and also provides JSON that is friendlier from javascript).

Work on the union type discriminator is here:

https://github.com/mbryzek/apidoc/pull/393

and starting to look into the JSON readers and writers

**Comment by mbryzek** [comment]
Have released apidoc this weekend w/ a major refactoring of the underlying json writers. I've tested locally and this service now compiles. Would you mind giving it a try to confirm if the new version solves this problem?
